target 'ALCoreDataManager', :exclusive => true do
  pod "ALCoreDataManager", :path => "../"

# pod 'RMPickerViewController', '~> 1.3.3'

end

target 'Tests', :exclusive => true do
  pod "ALCoreDataManager", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'OCMockito', '~> 1.0'

end
