target 'ALCoreDataManager', :exclusive => true do
  pod "ALCoreDataManager", :path => "../"

# pod 'RMPickerViewController', '~> 1.3.3'

end

target 'Tests', :exclusive => true do
  pod "ALCoreDataManager", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMockito'

end
