# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
pod install
- cd Example
- pod install
- cd ..
- xctool test -workspace Example/ALCoreDataManager.xcworkspace -scheme ALCoreDataManager -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
